name = "dreammaker-tier0"
main = "tier0.js"
compatibility_date = "2025-05-10"
compatibility_flags = ["nodejs_compat"]
account_id = "d902b91f0f1076e0601ffd6e7b4382c0"

[[kv_namespaces]]
binding    = "DM_KV"
id         = "ef1a164f23424e9a9b23721fb0d16133"
preview_id = "ef1a164f23424e9a9b23721fb0d16133"

[vars]
ENVIRONMENT = "production"
